name: Capture Screenshots with Capybara

on:
  push:
    branches:
      - main

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run application and capture screenshots with Capybara
      run: |
        # Run Capybara script to capture screenshots
        bundle exec ruby capture-screenshots.rb

    - name: Commit and push screenshots
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add screenshots
        git commit -m "Add screenshots"
        git push origin main
